name: Python 3.8-3.11

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov scipy==1.10.0
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=skysegmentor --cov-report=term --cov-report=xml --cov-report=html tests/

      - name: List files for debug
        run: |
          ls -alh
          ls -alh htmlcov || true
      
      - name: Upload coverage data
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: .coverage
      
      - name: Upload coverage HTML report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-${{ matrix.python-version }}
          path: htmlcov/

